<div class="col-xs-12 col-sm-8 mobile-mb-30">
	<div class="portfolio-info">
		<h2>Imitate the Ancient Painting Style</h2><br><br>
		<p>The artist’s imitating the ancient painting style, though it carries “imitation” in its name, is actually a product of rebirth. The “Imitating Ancient Painting Style” series did not originate from the artist’s intentional innovation, but rather from her admiration and fondness of Chinese classical paintings. Especially the fine and meticulous plant paintings of the Song dynasty, with their aesthetic mood of quiet observation, has found a great deal of resonance from the artist. Just like Su Shi(1037-1101), who upon reading the “Zhuang-tze” remarked: “I had many thoughts, yet not the words to express them. Today I have read this book, which says what I could not.” In light of such experiences, painters tend to dwell on them, and occasionally, designs from Chinese painting and calligraphy are introduced into the image of their works. Over time, the ideas in painting that attempt to fully investigate matters like the people of the Song dynasty did are integrated into the creative work.<br><br>
		Because experiencing “sketching from real life” is a common method that can be found in both Chinese and Western art, and is the one and only way in Chinese painting to capture a moving and vivid tone, the artist used to paint many still life line drawings of camellias, and then, using a transparent style of painting with brush and oil paint, created a series of small pieces with red and white camellias. These continuous pieces all have real life as the main theme. On the one hand, they have the composition of Western still life paintings, concretely depicting the main subject, with the background having the simple effect of flatness, causing the painting to exhibit a modern sketchy style. ON the other hand, the post of the plants is graceful and subdued, and the way the leaves are drawn are a realistic portrayal bursting with exuberance. All these belong to the fresh and refined approach to drawing flowers and plants by ancient Chinese painters. Along with that, painting pear flowers produces the aesthetic appeal of snapped-off twigs and branches; the composition is polished, and it’s clearly visible that it originated from the taste found in old paintings. The sense of liveliness from the example of Dong Shaw-hwei’s work is visible in all aspects of the detailed observations on the various demeanors of the way the plants grow; in the fanning out of the flower petals, the delicate brushwork, abundant with ancient thought, and full of taste.<br><br>
		As early as the oil painting tradition before the Renaissance era, the West has employed techniques of expression very similar to those of Chinese brush paintings. In the details of many picture books or oil paintings of the Middle Ages, a kind of vivid, meticulous, primitive, and elegant aesthetic can be seen. This type of flattened painting style has the same taste as the venerated brush paintings of the Tang and Song dynasties. This is perhaps the reason the artist used this specific style of oil brush painting to try out imitating this ancient style of paintings plants. Along the same line of reasoning, since the Ming and Qing dynasties, there has been a style of Chinese freehand ink paintings for which oil painting is unsuitable as a means of emulation. Therefore, the artist has used a watercolor style to paint a series of paintings imitating ancient landscape and plant paintings. “Flower, Bamboo & Rock in Garden, imitating Shi-tao’s style” was derived from just this, and as the artist greatly respects Shi-tao (1642-1707), this piece can be seen as a tribute toward Shi-tao.<br><br>
		The original 12-piece continuous screen of scroll painting by Shi-tao was overly large, so Dong Shaw-hwei shrank it and expressed it in a watercolor style, with fine and meticulous brushwork, refined and delicate colors, and despite the smaller size, the piece is still moving and moody. The wet painting style uses ink to add washes of color, continuing the intent behind the freehand painting of Chinese literatis. This could be referred to as achieving a new level, seeing and expressing with a different way. The artist had imitated three sets of 12-piece continuous watercolor paintings, showing the depth of her devotion to this work. Sadly, one of these was stolen many years ago, and has remained lost without a trace. The artist can’t let go of it, and can’t keep it out of her mind, and anticipates the day they will be reunited. In conclusion, the artist’s series of imitating the ancient painting style has a succinct composition, with delicate brushwork and graceful colors, with an especially refined and elegant character. It displays the focused concentration that went into the creation of these works, as well as the same calmness and harmony of the ancient people. It may well be said to exist in the space between the classic and the modern.<br><br>
		</p>
		<div class="btn-area text-center">
			<a href="../photos/index.php?/category/ancient&lang=zh_US" class="btn">More<i class="btn-fas fas fa-long-arrow-alt-right"></i></a>
		</div>
	</div>
</div>
<div class="col-xs-12 col-sm-4">
	<div class="portfolio-image mb-30">
		<img src="assets/img/portfolio/ancient/img1.jpg" alt="Pink Camellia, Imitate the Song Dynasty style- I" />
		<p class="no-margin fig">Pink Camellia, Imitate the Song Dynasty style- I &nbsp; 41 × 31.5 ㎝ &nbsp; Oil on Canvas &nbsp; 2005</p>
	</div>
	<div class="portfolio-image mb-30">
		<img src="assets/img/portfolio/ancient/img2.jpg" alt="Pear Blossoms, imitating the Song Dynasty style I" />
		<p class="no-margin fig">Pear Blossoms, imitating the Song Dynasty style I &nbsp; 50 × 60.5 cm &nbsp; Oil on Canvas &nbsp; 2006</p>
	</div>
	<div class="portfolio-image">
		<img src="assets/img/portfolio/ancient/img3.jpg" alt="Cymbidium ensifolium" />
		<p class="no-margin fig">Cymbidium ensifolium &nbsp; 41 × 31.5 ㎝ &nbsp; Oil on Canvas &nbsp; 2019</p>
	</div>
</div>